version: pending.{build}

skip_branch_with_pr: false
skip_commits:
  message: /!nobuild/
skip_tags: false

environment:
  fast_finish: true

init:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds.
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  
install:
  - cmd: choco install 7zip.commandline
  - cmd: pip install https://github.com/132nd-vWing/EMFT/archive/feature/init.zip#egg=emft

build_script:
  - cmd: for /f "delims=" %%i in ('git describe --tags') do set MISSION_VERSION=%%i
  - cmd: appveyor UpdateBuild -Version "%MISSION_VERSION%.%APPVEYOR_BUILD_NUMBER%"
  - cmd: emft recompose -f "%APPVEYOR_PROJECT_NAME%-%MISSION_VERSION%.miz"

test: off

artifacts:
  - path: '*.miz'
    name: mission
  
deploy:
  - provider: GitHub
    auth_token:
      secure: NsKzrR+oV1WGhR8oN9koVoosxhS4kEmuKqKG9p7DVEn4mlXb10VCXEzK8ADiDSIG
    artifact: 'mission'
    draft: false
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true